Module3 task1
htmlacademy-react/503315-what-to-watch-5 pull request #5
Opened 2020-10-15 13:24 UTC by puinka

2020-10-18 15:13 UTC, LonelyDutchhound reviewed
С propTypes ты немного запуталась. Смотри внимательно, что ты передаешь - и как ты это описываешь. То, что propTypes - это объект - означает, что он описывает другой объект - props, а не объекты внутри props. 
const { something } = props значит то же, что, условно, props. something = something;
То, что внутри propTypes описывает props, а не something.

2020-10-18 15:13 UTC, LonelyDutchhound commented on src/mocks/reviews.js
> +  {
Ревью тоже нужны id

2020-10-18 15:13 UTC, LonelyDutchhound commented on src/components/movie-screen/propTypes.js
> +export const propTypes = {
Этот объект стоит обозначить как тип film и вынестив отдельный файл, тогда ты сможешь им же описать тип данных films в App компоненте, в Movies-List'е, и им же описать отдельный фильм тут.

2020-10-18 15:13 UTC, LonelyDutchhound commented on src/components/add-review-screen/propTypes.js
> +export const propTypes = {
В пропТайпсах ты описываешь набор примитивов, а в компонент передаешь - посмотри что...

2020-10-25 05:56 UTC, LonelyDutchhound commented on src/components/add-review-screen/add-review-screen.jsx
> +    // этот код не меняет state
Он абсолютно точно меняет стейт, то, что дев тулзы запаздывают - проблема дев тулзов. Ты можешь убедиться в том, что все меняется, передавая в сетСтейт второй колбек: 
```
this.setState((state) => Object.assign(
        state,
        {rating}
    ), () => console.log(this.state));
```
Второй колбек выполняется ВСЕГДА СТРОГО ПОСЛЕ изменения стейта. Поскольку сетСтейт асинхронная ф-ция, т.е. вполняется НЕ моментально.
https://medium.com/@baphemot/understanding-reactjs-setstate-a4640451865b

2020-10-25 05:56 UTC, LonelyDutchhound commented on src/components/add-review-screen/add-review-screen.jsx
> +    // Этот код не перерисовывает компонент:
Перерисовывает, см комментарий к onRatingChange, или какой именно перерисовки ты ждешь?

2020-10-25 05:56 UTC, LonelyDutchhound commented on src/components/add-review-screen/add-review-screen.jsx
> +                  // звезды меняют цвет вне зависимости от того поменялся state или нет
Цвет звезд никак не зависит от стейта и задан через стили(css) в зависимости от checked элемента, и тебе не нужно это менять.

2020-10-25 05:56 UTC, LonelyDutchhound commented on src/mocks/utils.js
> +export const generateId = () => Math.floor(Math.random() * Date.now());
Класс! 👍

2020-10-31 16:08 UTC, sahaviev requested changes
Нужны доработки - обо всем рассказал на консультации.

2020-11-01 17:29 UTC, sahaviev commented on src/components/add-review-screen/add-review-screen.jsx
> +    this.setState({
Очень советую протестировать работу функции **setState**.
@LonelyDutchhound то что вы написали работает не так, это касается redux, но не setState)

2020-11-01 17:33 UTC, sahaviev commented on src/components/main/main.jsx
> +              <h2 className="movie-card__title">{movies[0].title}</h2>
Вытащи **movies[0]** в отдельную константу и используй ее, например так:
`const mainMovie = movies[0];`

2020-11-01 17:34 UTC, sahaviev commented on src/components/movie-card/movie-card.jsx
> +      onMouseOut={handleCardMouseOut}>
Привыкай переносить закрывашки на следующую строку везде)

2020-11-01 17:37 UTC, sahaviev commented on src/components/my-list-screen/my-list-screen.jsx
> +import {Link} from "react-router-dom";
Сперва должны идти импорты библиотечных функций, затем уже те что ты написала)

2020-11-01 17:38 UTC, sahaviev commented on src/mocks/movies.js
> +export default [
Можно тоже сделать не default экспорт, а именованный:
`export const movies = [`

2020-11-01 17:39 UTC, sahaviev commented on src/mocks/reviews.js
> +    id: generateId(),
Здесь забыла удалить **generateId** и добавить статичные.

2020-11-01 17:40 UTC, sahaviev commented on src/types/review-types.js
> +}).isRequired;
Здесь **isRequired** лучше убрать и отдать это на усмотрение компонентов которые будут использовать filmPropTypes

2020-11-01 17:40 UTC, sahaviev commented on src/types/review-types.js
> +export const film = PropTypes.shape({
film -> **filmPropTypes**

2020-11-01 17:41 UTC, sahaviev approved these changes
Я оставил комментарии. Не забудь почитать и пофиксить.
PR аппрувнул, двигайся дальше 🙂

2020-11-01 17:41 UTC, merged